# Context Root
server:
   port: 8081
   servlet:
      context-path: /employeedev
# ==============================================================================
# Mongodb connection
   data:
      mongodb:
         #host: 10.88.0.12
         host: localhost
         port: 27017
         database: employee
         #username: 
         #password: 
         #username: gqapdevappuser
         #password: Lxc79M6uwAW8RIFyuSZHR3Gchsg6KYGjlGgiiaAC
